# Generated by Django 4.2.7 on 2024-04-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=66)),
                ('lastname', models.CharField(max_length=110)),
                ('username', models.CharField(max_length=110)),
                ('password', models.CharField(max_length=444)),
                ('email', models.CharField(max_length=110, unique=True)),
                ('mobile', models.CharField(max_length=31)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_card_number', models.CharField(max_length=21)),
                ('joining_date', models.DateField()),
                ('designation', models.CharField(max_length=11)),
                ('home_address', models.CharField(blank=True, max_length=444, null=True)),
                ('is_active_user', models.BooleanField(default=True)),
                ('user_roles', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
