# Generated by Django 5.1.7 on 2025-04-15 10:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('B2B', 'Business to Business'), ('B2C', 'Business to Customer')], max_length=11)),
                ('visa_type', models.CharField(blank=True, choices=[('Resident', 'Resident with Emirates ID'), ('GCC', 'GCC National'), ('Tourist', 'Tourist')], max_length=66, null=True)),
                ('id_card_no', models.CharField(blank=True, max_length=110, null=True, unique=True)),
                ('id_issued_by', models.CharField(blank=True, max_length=110, null=True)),
                ('id_issue_date', models.DateField(blank=True, null=True)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('license_no', models.CharField(max_length=110, unique=True)),
                ('license_issued_by', models.CharField(blank=True, max_length=110, null=True)),
                ('license_issue_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=110)),
                ('last_name', models.CharField(max_length=110)),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('not knows', 'not known')], max_length=11, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone Number')),
                ('relation_type', models.CharField(blank=True, choices=[('B2C-Direct', 'B2C-Direct Customer'), ('B2C-CommissionAgent', 'B2C-Commission Agent'), ('B2C-Indirect', 'B2C-Commission Agent Customer')], max_length=66, null=True)),
                ('reference', models.CharField(blank=True, max_length=110, null=True)),
                ('companyname', models.CharField(max_length=66, unique=True)),
                ('tradeLicence', models.CharField(max_length=66, unique=True)),
                ('trafficCode', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ownername', models.CharField(max_length=110)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
