# Generated by Django 4.2.7 on 2024-07-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleName', models.CharField(max_length=110)),
                ('companyName', models.CharField(max_length=110)),
                ('noPlate', models.CharField(max_length=11)),
                ('vehicleCondition', models.CharField(max_length=11)),
                ('purchasedFrom', models.CharField(blank=True, max_length=110, null=True)),
                ('vehcileModel', models.CharField(max_length=12)),
                ('purchasingDate', models.DateField(blank=True, null=True)),
                ('sellingDate', models.DateField(blank=True, null=True)),
                ('ownershipStatus', models.CharField(max_length=21)),
                ('rentStatus', models.CharField(max_length=31)),
                ('vehicleColor', models.CharField(max_length=21)),
                ('chasesNo', models.CharField(max_length=66)),
                ('engineNo', models.CharField(max_length=66)),
                ('ownerName', models.CharField(max_length=110)),
                ('lastServiceDate', models.DateField()),
                ('nextServiceDate', models.DateField()),
                ('totalServiceKM', models.IntegerField()),
                ('lastServiceKM', models.IntegerField()),
                ('nextServiceKM', models.IntegerField()),
                ('lastCarPassingDate', models.IntegerField()),
                ('nextCarPassingDate', models.IntegerField()),
                ('purchasingPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sellingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vehicleStatus', models.CharField(max_length=31)),
                ('kmRangePerDay', models.IntegerField()),
                ('extraChargesPerKM', models.DecimalField(decimal_places=2, max_digits=11)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
