# Generated by Django 4.2.7 on 2024-07-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='lastCarPassingDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='nextCarPassingDate',
            field=models.DateField(),
        ),
    ]
